// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AdminTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void loginadminfuncoesadmin() {
    driver.get("http://localhost:5500/login.html");
    driver.manage().window().setSize(new Dimension(857, 542));
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("edwillerdelima@gmail.com");
    driver.findElement(By.id("senha")).sendKeys("123456");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector("tr:nth-child(1) .btn-editar")).click();
    driver.findElement(By.id("nome")).click();
    driver.findElement(By.id("nome")).sendKeys("Edwilleraraujo");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("edwiller2@gmail.com");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) .btn-excluir")).click();
    assertThat(driver.switchTo().alert().getText(), is("Deseja realmente desativar este usuário?\n\nApós a desativação, o usuário não poderá acessar o sistema."));
    driver.switchTo().alert().accept();
    assertThat(driver.switchTo().alert().getText(), is("Usuário desativado com sucesso."));
    driver.findElement(By.id("sair")).click();
  }
}
